
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you'd want to handle this more gracefully.
  // For this environment, we assume it's always available.
  console.warn("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });
const model = 'gemini-2.5-flash-image';

export async function removeWatermark(
  originalImageBase64: string,
  mimeType: string,
  maskBase64: string,
  userPrompt: string
): Promise<string> {
  const systemPrompt = `You are an expert image editor specializing in inpainting. 
The user has provided an original image and a mask image. 
The white area in the mask image indicates the region to be removed from the original image.
Your task is to remove the content within the masked area and fill it with a realistic background that seamlessly blends with the surrounding pixels and context.
Pay close attention to textures, lighting, and patterns to make the edit undetectable.`;
  
  const fullPrompt = userPrompt 
    ? `${systemPrompt}\n\nUser guidance: "${userPrompt}"`
    : systemPrompt;

  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        { text: fullPrompt },
        {
          inlineData: {
            data: originalImageBase64,
            mimeType: mimeType,
          },
        },
        {
          inlineData: {
            data: maskBase64,
            mimeType: 'image/png', // Mask is always PNG
          },
        },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const firstPart = response.candidates?.[0]?.content?.parts?.[0];
  if (firstPart && firstPart.inlineData) {
    return firstPart.inlineData.data;
  }
  
  throw new Error("No image was generated by the model.");
}
